backend:
  name: github # for github/decap local only
  # name: git-gateway # for netlify (possible identity which is stoopid and dumb and bad)
  repo: melrieoi/lyrics
  # site_url: https://melrieoi.github.io/lyrics # for github/decap local only
  site_url: https://melrieoilyrics.netlify.app # for netlify
  branch: main

media_folder: "uploads" # Folder for images
public_folder: "/uploads"

# media_folder: "BandImages"  # Folder for images
# public_folder: "/BandImages"

collections:
  - name: "bands"
    label: "Bands"
    folder: "Bands"
    extension: "json"
    format: "json"
    create: true
    slug: "{{bandName | slug}}"
    identifier_field: "bandName" # Ensures the entry is identified by band name, not an ID
    fields:
      - { name: "bandName", label: "Band Name", widget: "string" }
      - { name: "image", label: "Band Image", widget: "image", required: false }
      - name: "albums"
        label: "Albums"
        widget: "list"
        fields:
          - { name: "albumName", label: "Album Name", widget: "string" }
          - { name: "year", label: "Year", widget: "number", required: false }
          - name: "songs"
            label: "Songs"
            widget: "list"
            fields:
              - { name: "songName", label: "Song Name", widget: "string" }
              - { name: "lyrics", label: "Lyrics", widget: "text", required: false }

# dont remember what this is exactly but its old and bad and idk shit...
  # - name: "lyrics"
  #   label: "Lyrics"
  #   folder: "lyrics"
  #   create: true
  #   format: "json"
  #   slug: "{{title | slug}}"
  #   identifier_field: "title"
  #   fields:
  #     - { name: "title", label: "Title", widget: "string" }
  #     - { name: "artist", label: "Artist", widget: "string" }
  #     - { name: "album", label: "Album", widget: "string" }
  #     - { name: "lyrics", label: "Lyrics", widget: "text" }