backend:
  name: github
  repo: melrieoi/lyricssite
  branch: main
  auth_scope: repo
  site_url: https://melrieoi.github.io/lyricssite
  base_url: https://api.github.com
  client_id: Ov23liSrCxh29swMbYm3
  client_secret: 868f287c6242bc3803f20c47210fd0dde1131424

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "lyrics"
    label: "Lyrics"
    folder: "lyrics"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "artist", label: "Artist", widget: "string" }
      - { name: "album", label: "Album", widget: "string" }
      - { name: "lyrics", label: "Lyrics", widget: "markdown" }