backend:
  name: git-gateway
  branch: main  # Adjust to your repo's branch

media_folder: "uploads"  # Where images/files are stored
public_folder: "/uploads"

collections:
  - name: "lyrics"
    label: "Lyrics"
    folder: "lyrics"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "artist", label: "Artist", widget: "string" }
      - { name: "album", label: "Album", widget: "string" }
      - { name: "lyrics", label: "Lyrics", widget: "markdown" }