// shows all bands for bands.html
fetch("bands.json") // This file is auto-generated by CMS
    .then(response => response.json())
    .then(bands => {
        let container = document.getElementById("bandsdiv");
        bands.forEach(band => {
            let div = document.createElement("div");
            // let imageSrc = band.image ? `../lyrics/${band.image}` : "../lyrics/uploads/placeholder.png";
            let imageSrc = band.image ? `../${band.image}` : "../uploads/placeholder.png";

            div.setAttribute('id', 'band');
            div.innerHTML = `
                <img src="${imageSrc}" alt="${band.bandName}">
                <a href="band.html?band=${band.filename}">${band.bandName}</a>
            `;
            container.appendChild(div);
        });
    });