// shows all bands for bands.html
fetch("../lyrics/Bands/thedatabase.json") // This file is auto-generated by CMS
    .then(response => response.json())
    .then(person => {
        let container = document.getElementById("bandsdiv");
        person.forEach(persons => {
            let div = document.createElement("div");

            div.setAttribute('id', 'band');
            div.innerHTML = `
                <a>${persons.name}</a>
                <p>${persons.status}</p>
            `;
            container.appendChild(div);
        });

    });
